# Etapa 1 - Instalar dependências e criar o aplicativo
FROM debian:latest AS build-env

# Instalar dependências do flutter
RUN apt-get update 
RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3
RUN apt-get clean

# Clonar o repositório do flutter
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter

# Definir o caminho do flutter
# RUN /usr/local/flutter/bin/flutter doctor -v
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Executar flutter doctor
RUN flutter doctor -v
# Habilitar flutter web
RUN flutter channel master
RUN flutter upgrade
RUN flutter config --enable-web

# Copiar os arquivos para o contêiner e criar
RUN mkdir /app/
COPY . /app/
WORKDIR /app/
RUN flutter build web

# Etapa 2 - Criar a imagem NGINX
FROM nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html